"""Add role to UserModel

Revision ID: 83b59ab3dd98
Revises: bdfba66a6f61
Create Date: 2023-01-26 06:49:44.875967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b59ab3dd98'
down_revision = 'bdfba66a6f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), server_default='user', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
